name: Newman CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Create directory
        run: |
          mkdir -p SampleArtifacts

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Collection
        run: |
          newman run "BABE-IMP Automation.postman_collection.json" -e "BABE Environment.postman_environment.json"

      - name: Generate Report
        run: |
          newman run "BABE-IMP Automation.postman_collection.json" -e "BABE Environment.postman_environment.json" -d IMP_TestData -r htmlextra --reporter-htmlextra-export SampleArtifacts/report.html

      - name: Publish Report
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: SampleArtifacts
